########################################################################################################################
#APPLICATION
########################################################################################################################
spring.application.name=virtual-card-platform
spring.messages.basename=messages
spring.web.resources.add-mappings=false
spring.messages.encoding=UTF-8
server.port=${PORT:9090}
spring.batch.jdbc.initialize-schema=ALWAYS
spring.batch.job.enabled=false
