########################################################################################################################
#APPLICATION
########################################################################################################################
spring.application.name=virtual-card-platform
spring.messages.basename=messages
spring.web.resources.add-mappings=false
spring.messages.encoding=UTF-8
server.port=8080

########################################################################################################################
# MONGODB (STAGING / RAW DATA)
########################################################################################################################
spring.data.mongodb.uri=mongodb://localhost:27017/virtual-card-platform

########################################################################################################################
# DATASOURCE - POSTGRESQL (DOCKER)
########################################################################################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/virtual-card-platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

########################################################################################################################
# JPA / HIBERNATE
########################################################################################################################
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

# Batch optimizations
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

########################################################################################################################
# FLYWAY
########################################################################################################################
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

########################################################################################################################
# SPRING BATCH
########################################################################################################################
spring.batch.jdbc.initialize-schema=ALWAYS
spring.batch.job.enabled=false

########################################################################################################################
# LOGGING (PROD-SAFE DEFAULT)
########################################################################################################################
logging.level.org.springframework.batch=INFO
logging.level.org.springframework.jdbc.core=INFO
logging.level.org.hibernate.SQL=OFF
