package br.com.rhribeiro25.virtual_card_platform.domain.model.enums;

public enum BatchAuditImportStatus {
    AUDIT_PERSISTED,
    AUDIT_NO_ACTION,

    CARD_PERSISTED,
    CARD_UPDATED,
    CARD_NO_ACTION,

    TRANSACTION_PERSISTED,
    TRANSACTION_UPDATED,
    TRANSACTION_NO_ACTION,

    PROVIDER_PERSISTED,
    PROVIDER_UPDATED,
    PROVIDER_NO_ACTION,

    CARD_PROVIDER_PERSISTED,
    CARD_PROVIDER_UPDATED,
    CARD_PROVIDER_NO_ACTION,

    SUCCESSFUL
}
