@startuml
actor user as "Client App"

box "API Layer" #LightBlue
participant "CardController" as controller <<(C,#ADD1B2)>>
end box

box "Application Layer" #LightGreen
participant "CardUsecase" as usecase <<(C,#ADD1B2)>>
end box

box "Infrastructure Layer" #LightCoral
participant "CardRepository" as cardRepo <<(I,#ADD1B2)>>
end box

database "Cache" as cache #MediumBlue
database "H2 Database" as db #MediumBlue

user -> controller : POST /cards
controller -> usecase : createCard()
usecase -> cardRepo : save()
cardRepo -> db : INSERT card
db --> cardRepo : OK
cardRepo -> cache : update cache with new card
cache --> cardRepo : OK
cardRepo --> usecase : card
usecase --> controller : CardDTO
controller --> user : 201 Created + card info
@enduml