# -----------------------------------------------
# 🚀 CD - Deploy and Promote to Heroku by Tag
# -----------------------------------------------
name: CD - Deploy and Promote to Heroku by Tag

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'Tag to promote from (e.g. v1.0.0-dev)'
        required: false
      to_env:
        description: 'Target environment (hml or prd)'
        required: false
        type: choice
        options:
          - hml
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🧠 Detect context (release or manual)
        id: detect
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG_NAME="${GITHUB_REF##*/}"
            ENV_SUFFIX="${TAG_NAME##*-}"
          else
            TAG_NAME="${{ inputs.from_tag }}"
            ENV_SUFFIX="${{ inputs.to_env }}"
            git fetch --tags
            git checkout tags/${TAG_NAME} -b promote-${ENV_SUFFIX}
          fi

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "ENV_SUFFIX=$ENV_SUFFIX" >> $GITHUB_ENV
          echo "APP_NAME=virtual-card-platform-$ENV_SUFFIX" >> $GITHUB_ENV

      - name: 🛠️ Build with Maven
        run: mvn clean package -DskipTests

      - name: 🚀 Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          SPRING_PROFILES_ACTIVE: ${{ env.ENV_SUFFIX }}
        run: |
          echo "Deploying tag $TAG_NAME to '$ENV_SUFFIX'..."
          echo "Using app name: '$APP_NAME'"

          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
          heroku config:set SPRING_PROFILES_ACTIVE=$ENV_SUFFIX --app "$APP_NAME"
          heroku container:push web --app "$APP_NAME"
          heroku container:release web --app "$APP_NAME"