# -----------------------------------------------
# 🚀 CD - Deploy and Promote to Heroku
# -----------------------------------------------
name: CD - Deploy and Promote to Heroku

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'Tag (v1.0.0)'
        required: true
      to_env:
        description: 'Env (hml or prd)'
        required: true
        default: hml
        type: choice
        options:
          - hml
          - prd

jobs:
  deploy-dev:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: dev
      TAG_NAME: ${{ github.ref_name }}
      APP_NAME: virtual-card-platform-dev
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: mvn clean package -DskipTests

      - name: 🐳 Deploy to Heroku (dev)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          SPRING_PROFILES_ACTIVE: dev
        run: |
          echo "Deploying ${TAG_NAME} to development..."
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
          heroku config:set SPRING_PROFILES_ACTIVE=dev --app $APP_NAME
          heroku container:push web --app $APP_NAME
          heroku container:release web --app $APP_NAME

  promote:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.inputs.from_tag }}
      DEPLOY_ENV: ${{ github.event.inputs.to_env }}
    steps:
      - name: 🔁 Promote from ${{ env.TAG_NAME }} to ${{ env.DEPLOY_ENV }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "Promoting $TAG_NAME to $DEPLOY_ENV..."

          if [[ "$DEPLOY_ENV" == "hml" ]]; then
            APP_NAME=virtual-card-platform-hml
          elif [[ "$DEPLOY_ENV" == "prd" ]]; then
            APP_NAME=virtual-card-platform-prd
          else
            echo "❌ Invalid target environment: $DEPLOY_ENV"
            exit 1
          fi

          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
          heroku config:set SPRING_PROFILES_ACTIVE=$DEPLOY_ENV --app "$APP_NAME"
          heroku container:push web --app "$APP_NAME"
          heroku container:release web --app "$APP_NAME"
