# -----------------------------------------------
# 🚀 CD - Deploy to Heroku by tag environment
# -----------------------------------------------
name: CD - Deploy to Heroku by tag environment

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: mvn clean package -DskipTests

      - name: 🧠 Detect environment
        id: env-detect
        run: |
          TAG_NAME="${GITHUB_REF##*/}"  # Extrai somente o nome da tag
          ENV_SUFFIX="${TAG_NAME##*-}"  # Pega somente o final após o último hífen

          echo "TAG_NAME=$TAG_NAME"
          echo "ENV_SUFFIX=$ENV_SUFFIX"

          if [[ "$ENV_SUFFIX" =~ ^(dev|hml|prd)$ ]]; then
            echo "env=$ENV_SUFFIX" >> $GITHUB_OUTPUT
            echo "APP_NAME=virtual-card-platform-$ENV_SUFFIX" >> $GITHUB_OUTPUT
          else
            echo "❌ Ambiente desconhecido: $ENV_SUFFIX"
            exit 1
          fi
      

      - name: 🚀 Deploy to Heroku
        if: steps.env-detect.outputs.env != ''
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          SPRING_PROFILES_ACTIVE: ${{ steps.env-detect.outputs.env }}
        run: |
          echo "Deploying to '${{ steps.env-detect.outputs.env }}'..."
          echo "Using app name: '${{ steps.env-detect.outputs.APP_NAME }}'"

          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login

          heroku config:set SPRING_PROFILES_ACTIVE=${{ steps.env-detect.outputs.env }} --app "${{ steps.env-detect.outputs.APP_NAME }}"
          heroku container:push web --app "${{ steps.env-detect.outputs.APP_NAME }}"
          heroku container:release web --app "${{ steps.env-detect.outputs.APP_NAME }}"
