# -----------------------------------------------
# 🚀 CD - Deploy to Heroku by tag environment
# -----------------------------------------------
name: CD - Deploy to Heroku by tag environment

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: mvn clean package -DskipTests

      - name: 🧠 Detect environment
        id: env-detect
        run: |
          if [[ "${{ github.ref_name }}" == *-dev ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == *-hml ]]; then
            echo "env=hml" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == *-prd ]]; then
            echo "env=prd" >> $GITHUB_OUTPUT
          else
            echo "❌ Tag sem ambiente conhecido. Encerrando..."
            exit 1
          fi

      - name: 🚀 Deploy to Heroku
        if: steps.env-detect.outputs.env != ''
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          SPRING_PROFILES_ACTIVE: ${{ steps.env-detect.outputs.env }}
        run: |
          echo "Deploying to ${{ steps.env-detect.outputs.env }}..."
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login

          # Mapeando app name com base no ambiente
          if [ "${{ steps.env-detect.outputs.env }}" == "dev" ]; then
            APP_NAME=${{ secrets.HEROKU_APP_NAME_DEV }}
          elif [ "${{ steps.env-detect.outputs.env }}" == "hml" ]; then
            APP_NAME=${{ secrets.HEROKU_APP_NAME_HML }}
          elif [ "${{ steps.env-detect.outputs.env }}" == "prd" ]; then
            APP_NAME=${{ secrets.HEROKU_APP_NAME_PRD }}
          fi

          heroku container:push web --app "$APP_NAME"
          heroku container:release web --app "$APP_NAME"
